Feat
it-kyrylo/project-b pull request #4
Opened 2021-09-02 14:43 UTC by vladimirdonev

Added some Features

2021-09-02 15:41 UTC, VeselinMetodiev commented
Good.

2021-09-03 08:03 UTC, it-kyrylo requested changes
Good!

2021-09-03 08:03 UTC, it-kyrylo commented on ProjectB/ProjectB/appsettings.json
> -  "ApiConfiguration": {
why have you deleted it?

2021-09-06 09:25 UTC, it-kyrylo approved these changes

2021-09-07 20:27 UTC, merged