Added caching feature
it-kyrylo/project-b pull request #6
Opened 2021-09-02 17:14 UTC by aico60

2021-09-03 08:45 UTC, it-kyrylo requested changes
I think the only good place for caching it is `GetHotelDetailsById` so please remove all caching stuff from `GetDestinationIdAsync` and `GetHotelsByDestinationIdAsync`

also please take a look at how I implemented ICacheFilter, and try to run it locally and fix all problems if you find them, and I swear you will find them ;)

2021-09-03 08:45 UTC, it-kyrylo commented on ProjectB/ProjectB/Infrastructure/CacheFilter.cs
> +    public class CacheFilter
Add ICacheFilter for this class

2021-09-03 08:45 UTC, it-kyrylo commented on ProjectB/ProjectB/Services/HotelService.cs
> +        public HotelService(IHotelClients hotelClients, IMapper mapper, CacheFilter cacheFilter)
same use ICacheFilter instead of CacheFilter

2021-09-03 15:48 UTC, aico60 commented
Changes done and waiting for review.

2021-09-04 15:55 UTC, vladimirdonev commented
Approve!

2021-09-06 09:27 UTC, it-kyrylo approved these changes

2021-09-06 18:38 UTC, VeselinMetodiev commented
I Approve! Good job, Aykut!

2021-09-06 20:25 UTC, merged